# Generated by Django 4.2.2 on 2023-07-15 06:57

from django.conf import settings
from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0007_trend'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('icon', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='recipients',
            field=models.ManyToManyField(blank=True, related_name='received_recs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='media_type',
            field=models.ForeignKey(default=post.models.get_media_type_id, on_delete=models.SET(post.models.get_media_type), to='post.mediatype'),
        ),
    ]
