# Generated by Django 4.2.2 on 2023-07-18 04:30

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_mediatype_post_recipients_post_title_post_media_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='media_type',
            field=models.ForeignKey(default=post.models.get_media_type_id, on_delete=models.SET(post.models.get_media_type), related_name='posts', to='post.mediatype'),
        ),
    ]
