# Generated by Django 4.2.2 on 2023-08-19 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_alter_comment_created_by_alter_like_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='type_of_report',
            field=models.CharField(choices=[('threats', 'Threats of violence'), ('harassment', 'Harassment'), ('pornography', 'Pornographic content'), ('spam', 'Spam'), ('privacy', 'Privacy violation'), ('copyright', 'Copyright violation'), ('terms', 'Terms of Service violation'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
