# Generated by Django 4.2.2 on 2023-09-03 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0016_alter_genre_options_post_saves_count_save_post_saves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='save',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_recs', to=settings.AUTH_USER_MODEL),
        ),
    ]
