# Generated by Django 4.2.2 on 2023-09-03 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0017_alter_save_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='saves',
            new_name='saved_recs',
        ),
    ]
